DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    USER_ID int PRIMARY KEY AUTO_INCREMENT,
    USER_NAME TEXT,
    USER_ROLE TEXT,
    USER_ADDRESS VARCHAR(50)
);


DROP TABLE IF EXISTS ORDER;

CREATE TABLE ORDER
(
    ORDER_ID int PRIMARY KEY AUTO_INCREMENT,
    PIZZA_NUMBER INT,
    PIZZA_SIZE VARCHAR(15),
    ORDER_TOTAL VARCHAR(15),
    ORDER_STATUS VARCHAR(15),
    ORDER_DATE DATE
);


DROP TABLE IF EXISTS TOPPING;

CREATE TABLE TOPPING
(
    TOPPING_ID int PRIMARY KEY AUTO_INCREMENT,
    TOPPING_NAME VARCHAR(50),
    TOPPING_PRICE VARCHAR(50),
    ORDER_ID INT,
     FOREIGN KEY(ORDER_ID) REFERENCES ORDER(ORDER_ID)
);





